

#  what is namespace = it creates folder or just like room(virtual boundary)
#  significance - onto one kubernetes cluster we coudl run many application 

#  Apply: kubectl apply -f k8s/namespace.yaml


apiVersion: v1
kind: Namespace
metadata:
  name: emergencyq
  labels:
    app: emergencyq
    managed-by: kubectl
