
#  nginx.conf — EmergencyQ Frontend
#
#  Nginx what does here:
#  1. React built files serves 
#  2. /api/* requests forwards to backend
#  3. Returns index.html for React Router
#
#  This file copy in Dockerfile.frontend


server {

    # listen on port 80 (HTTP default)
    listen 80;

    # React built files location
    root /usr/share/nginx/html;

    # Default file serves
    index index.html;


    # Rule 1: React Router Support  

        # Problem:  If the user directly visits or refreshes /complaint,
        # Nginx tries to find a file named "complaint"
        # File not found → 404 error

        # Fix: Return index.html for every URL
        # React Router will handle the routing itself   

    location / {
        try_files $uri $uri/ /index.html;
        #   ↑             ↑         ↑
        #   exact file    folder    fallback:  handles react
    }


    # Rule 2: API Proxy 
    
    # Problem: The frontend makes requests to /api/analyze
    #          but Nginx does not know where to forward them

    # Fix: Forward all requests starting with /api/ to the backend

    # "backend" = the service name defined in docker-compose.yml
# Docker automatically resolves "backend" to the correct container IP
    location /api/ {
        proxy_pass http://backend:8000;
        #                   ↑       ↑
        #          service name   backend's port

        # Send original request info to backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}
